name: App Flutter

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Clonado
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Dependencias del proyecto
        run: flutter pub get

      - name: Ejecutar tests
        run: flutter test

      - name: Construir APK
        run: flutter build apk --release

      - name: Construir AAB
        run: flutter build appbundle --release

      - name: Crear release y subir artefactos
        run: |
          gh release create "v1.0.${{ github.run_number }}" \
          build/app/outputs/flutter-apk/app-release.apk \
          build/app/outputs/bundle/release/app-release.aab
